# Generated by Django 4.2.1 on 2023-05-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userview', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdblink',
            field=models.URLField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
