# Generated by Django 4.2.1 on 2023-05-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userview', '0003_movie_imdblink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='gallery',
            field=models.ManyToManyField(to='userview.image'),
        ),
    ]
