# Generated by Django 4.2.1 on 2023-05-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userview', '0006_alter_image_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='front_image',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
